# Server port (optional, default is 8080)
server.port=8080

# OpenWeather API Key (replace with your actual key)
openweather.api.key=6044ee6565fa2f80dbb9bc2222fc6463

# Optional: scheduler interval (in minutes)
alerts.scheduler.interval.minutes=60
